# Generated by Django 5.0.2 on 2024-09-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('is_interested', models.BooleanField(default=False)),
                ('is_not_interested', models.BooleanField(default=False)),
                ('is_eligible', models.BooleanField(default=True)),
                ('is_not_eligible', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
