# Generated by Django 5.0.2 on 2024-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_eligible',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_interested',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_not_eligible',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_not_interested',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
