# Generated by Django 5.0.2 on 2024-09-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_customer_is_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_interested',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_not_eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_not_interested',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
