# Generated by Django 5.0.2 on 2024-09-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_customer_is_eligible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('loan_id', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('present_loan_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('tenure', models.PositiveIntegerField(help_text='Loan tenure in months')),
                ('total_monthly_emi_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('emi_due_date', models.DateField()),
                ('emi_cleared', models.BooleanField(blank=True, null=True)),
                ('extended_due_date', models.DateField(blank=True, null=True)),
                ('critical_loan_status', models.CharField(choices=[('NORMAL', 'Normal'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('revisit_date', models.DateField(blank=True, null=True)),
                ('revisit_reason', models.TextField(blank=True, null=True)),
                ('due_date_pending_reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
