# Generated by Django 5.0.2 on 2024-09-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emi_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='present_loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_monthly_emi_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
