# Generated by Django 5.0.2 on 2024-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_loan_emi_cleared_alter_loan_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='visit_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
