# Generated by Django 5.0.2 on 2024-09-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_loan_visit_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='original_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
