# Generated by Django 5.0.2 on 2024-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_customuser_original_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emi_cleared',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
