# Generated by Django 5.0.2 on 2024-09-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_loan_emi_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='critical_loan_status',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10, null=True),
        ),
    ]
