# Generated by Django 5.0.2 on 2024-09-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_loan_critical_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='critical_loan_status',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='emi_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
